# Generated by Django 5.1.3 on 2026-05-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="Untitled Task", max_length=200),
            preserve_default=False,
        ),
    ]
